import {ClerkProvider} from '@clerk/nextjs'
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import {clsx} from "clsx";
import {dark} from "@clerk/themes";
import {GlobalUserContextProvider} from "@/context/context";
import {Toaster} from "@/components/ui/sonner";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Placement Portal", description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (<ClerkProvider appearance={{
        baseTheme: dark,
    }}>
        <html lang="en">
        <body className={clsx(inter.className, "w-full min-h-screen max-w-[2500px] p-4 lg:p-8")}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <GlobalUserContextProvider>
                {children}
                <Toaster theme={"system"} visibleToasts={5}/>
            </GlobalUserContextProvider>
        </ThemeProvider>
        </body>
        </html>
    </ClerkProvider>);
}
